"""Converts the trained recurrent decoder to fixed point through hls4ml, checks it against the network it came from, and emits its Verilog and wrapper parameters."""

import argparse
import os
import pathlib
import shutil
import sys

os.environ["CUDA_VISIBLE_DEVICES"] = ""

import hls4ml
import keras
import numpy as np
import stim
import torch

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "host" / "lib"))
sys.path.insert(0, str(ROOT / "host" / "train"))

from generate import DATA, read_ascii
from train_lstm import ABSENT, HIDDEN, WEIGHT_BITS, Decoder, detector_columns, quantize

FRACTION = 7
TABLE_SIZE = 1024
STRATEGY = "Resource"
REUSE = 64
CLOCK_PERIOD = 4
INTEGER = {"wi": 6, "wh": 4, "b": 3, "wd": 3, "bd": 2}
VALUE_INTEGER = 7
BUILD = ROOT / "build" / "recurrent"
GENERATED = pathlib.Path(__file__).parent / "generated"


def slots(circuit):
    columns = detector_columns(circuit)
    return {i: (int(c[2]), columns[(c[0], c[1])]) for i, c in circuit.get_detector_coordinates().items()}


def sequences(dets, places, timesteps, width):
    x = np.full((len(dets), timesteps, width), ABSENT, dtype=np.float32)
    for i, (t, column) in places.items():
        x[:, t, column] = dets[:, i]
    return x


def keras_model(weights, timesteps, width):
    model = keras.Sequential([
        keras.Input((timesteps, width)),
        keras.layers.LSTM(HIDDEN, activation="tanh", recurrent_activation="sigmoid", name="lstm"),
        keras.layers.Dense(1, name="dense"),
    ])
    model.get_layer("lstm").set_weights([weights["wi"].T, weights["wh"].T, weights["b"]])
    model.get_layer("dense").set_weights([weights["wd"].T, weights["bd"]])
    return model


def fixed(integer):
    return f"fixed<{integer + FRACTION},{integer},RND,WRAP>"


def hls_model(model):
    config = hls4ml.utils.config_from_keras_model(model, granularity="name", backend="Vitis")
    config["Model"].update(Precision=fixed(VALUE_INTEGER), Strategy=STRATEGY, ReuseFactor=REUSE)
    layers = config["LayerName"]
    layers["input_layer"]["Precision"]["result"] = fixed(VALUE_INTEGER)
    layers["lstm"].update(Strategy=STRATEGY, ReuseFactor=REUSE, RecurrentReuseFactor=REUSE, TableSize=TABLE_SIZE)
    layers["lstm"]["Precision"].update(
        weight=fixed(INTEGER["wi"]),
        recurrent_weight=fixed(INTEGER["wh"]),
        bias=fixed(INTEGER["b"]),
        recurrent_bias=fixed(INTEGER["b"]),
        accum=fixed(VALUE_INTEGER),
        result=fixed(VALUE_INTEGER),
    )
    layers["dense"].update(Strategy=STRATEGY, ReuseFactor=REUSE)
    layers["dense"]["Precision"].update(weight=fixed(INTEGER["wd"]), bias=fixed(INTEGER["bd"]), result=fixed(VALUE_INTEGER))
    return hls4ml.converters.convert_from_keras_model(
        model, hls_config=config, output_dir=str(BUILD), project_name="recurrent", backend="Vitis",
        part="xc7a100tcsg324-1", io_type="io_parallel", clock_period=CLOCK_PERIOD,
    )


def emit_params(places, timesteps, width, checkpoint):
    slot_count = timesteps * width
    det_w = max(1, (len(places) - 1).bit_length())
    present, source = 0, [0] * slot_count
    for i, (t, column) in places.items():
        present |= 1 << (t * width + column)
        source[t * width + column] = i
    body = ", ".join(f"{det_w}'d{s}" for s in reversed(source))
    return "\n".join([
        f"// Generated by rtl/recurrent/generate_rtl.py from {checkpoint}; regenerate rather than edit.",
        "`ifndef RECURRENT_PARAMS_SVH",
        "`define RECURRENT_PARAMS_SVH",
        "",
        f"localparam int FRACTION = {FRACTION};",
        f"localparam int VALUE_W = {VALUE_INTEGER + FRACTION};",
        f"localparam int SLOTS = {slot_count};",
        f"localparam int DET_W = {det_w};",
        "",
        f"localparam logic [SLOTS-1:0] PRESENT = {slot_count}'h{present:0{(slot_count + 3) // 4}x};",
        f"localparam logic [SLOTS*DET_W-1:0] SOURCE = {{{body}}};",
        "",
        "`endif",
    ]) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate the recurrent decoder RTL through hls4ml")
    parser.add_argument("checkpoint", type=pathlib.Path)
    args = parser.parse_args()

    circuit = stim.Circuit.from_file(DATA / "circuit.stim")
    places = slots(circuit)
    timesteps = 1 + max(t for t, _ in places.values())
    width = 1 + max(c for _, c in places.values())

    weights = {k: quantize(v, WEIGHT_BITS).numpy() for k, v in torch.load(args.checkpoint, map_location="cpu").items()}
    for name, bits in INTEGER.items():
        assert np.abs(weights[name]).max() < 2 ** (bits - 1), f"{name} does not fit {bits} integer bits"
    dets = read_ascii(DATA / "detectors.txt")
    truth = read_ascii(DATA / "observables.txt")[:, 0]
    x = sequences(dets, places, timesteps, width)

    network = Decoder(width, None, "standard")
    network.load_state_dict({k: torch.tensor(v) for k, v in weights.items()})
    with torch.no_grad():
        reference = network(torch.tensor(x), torch.ones(len(x), timesteps, dtype=torch.bool)).numpy() > 0

    hls = hls_model(keras_model(weights, timesteps, width))
    hls.compile()
    fixed = hls.predict(np.ascontiguousarray(x)).reshape(-1) > 0
    (DATA / "recurrent_expected.txt").write_text("".join(f"{int(b)}\n" for b in fixed))

    hls.build(csim=False, synth=True, cosim=False, export=False, vsynth=False, log_to_stdout=False)
    shutil.rmtree(GENERATED, ignore_errors=True)
    shutil.copytree(BUILD / "recurrent_prj" / "solution1" / "syn" / "verilog", GENERATED)
    for path in GENERATED.glob("*.v"):
        path.write_text(path.read_text().replace('$readmemh("./', f'$readmemh("{GENERATED.relative_to(ROOT).as_posix()}/'))
    (pathlib.Path(__file__).parent / "recurrent_params.svh").write_text(emit_params(places, timesteps, width, args.checkpoint.name))

    print(f"shots        {len(dets)}")
    print(f"network      {int((reference != truth).sum())} errors")
    print(f"fixed point  {int((fixed != truth).sum())} errors, {int((fixed != reference).sum())} disagreements with the network")
    print(f"wrote {GENERATED}")


if __name__ == "__main__":
    main()
