// Generated by rtl/recurrent/generate_rtl.py from recurrent-d3-p0.005-standard-6bit.pt; regenerate rather than edit.
`ifndef RECURRENT_PARAMS_SVH
`define RECURRENT_PARAMS_SVH

localparam int FRACTION = 7;
localparam int VALUE_W = 14;
localparam int SLOTS = 32;
localparam int DET_W = 5;

localparam logic [SLOTS-1:0] PRESENT = 32'ha5ffffa5;
localparam logic [SLOTS*DET_W-1:0] SOURCE = {5'd23, 5'd0, 5'd22, 5'd0, 5'd0, 5'd21, 5'd0, 5'd20, 5'd15, 5'd19, 5'd18, 5'd14, 5'd17, 5'd13, 5'd12, 5'd16, 5'd7, 5'd11, 5'd10, 5'd6, 5'd9, 5'd5, 5'd4, 5'd8, 5'd3, 5'd0, 5'd2, 5'd0, 5'd0, 5'd1, 5'd0, 5'd0};

`endif
