"""Emits the synthesisable layer, core and parameter files for the weightless decoder from an exported model."""

import argparse
import json
import pathlib


def lut_init(table):
    value = 0
    for addr, bit in enumerate(table):
        value |= (bit & 1) << addr
    return f"{len(table)}'h{value:0{(len(table) + 3) // 4}X}"


def header(name):
    return f"// Generated by rtl/generate_rtl.py from {name}; regenerate rather than edit.\n"


def emit_layer(index, layer, in_bits, name):
    mapping, luts = layer["mapping"], layer["luts"]
    n = len(mapping[0])
    lines = [header(name), f"module dwn_layer{index} ("]
    lines.append(f"    input  logic [{in_bits - 1}:0] in,")
    lines.append(f"    output logic [{len(mapping) - 1}:0] out")
    lines.append(");")
    for i in range(len(mapping)):
        pins = ", ".join(f"in[{mapping[i][k]}]" for k in reversed(range(n)))
        lines.append(
            f"    lut_node #(.N({n}), .INIT({lut_init(luts[i])})) "
            f"lut{i} (.addr({{{pins}}}), .out(out[{i}]));"
        )
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


def emit_core(sizes, in_bits, name):
    lines = [header(name), "module dwn_core ("]
    lines.append("    input  logic clk,")
    lines.append("    input  logic rst,")
    lines.append(f"    input  logic [{in_bits - 1}:0] in,")
    lines.append(f"    output logic [{sizes[-1] - 1}:0] out")
    lines.append(");")
    for i, size in enumerate(sizes, start=1):
        src = "in" if i == 1 else f"layer{i - 1}_bits"
        lines.append(f"    logic [{size - 1}:0] layer{i}_comb;")
        lines.append(f"    logic [{size - 1}:0] layer{i}_bits;")
        lines.append(f"    dwn_layer{i} u_layer{i} (.in({src}), .out(layer{i}_comb));")
        lines.append("")
    lines.append("    always_ff @(posedge clk) begin")
    lines.append("        if (rst) begin")
    for i in range(1, len(sizes) + 1):
        lines.append(f"            layer{i}_bits <= '0;")
    lines.append("        end else begin")
    for i in range(1, len(sizes) + 1):
        lines.append(f"            layer{i}_bits <= layer{i}_comb;")
    lines.append("        end")
    lines.append("    end")
    lines.append("")
    lines.append(f"    assign out = layer{len(sizes)}_bits;")
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


def emit_params(meta, sizes, name):
    group = meta["group_size"]
    lines = [header(name), "`ifndef DWN_PARAMS_SVH", "`define DWN_PARAMS_SVH"]
    lines.append(f"`define WL_IN_BITS    {meta['input_size']}")
    lines.append(f"`define WL_OUT_BITS   {sizes[-1]}")
    lines.append(f"`define WL_GROUP_SIZE {group}")
    lines.append(f"`define WL_SCORE_W    {max(1, group.bit_length())}")
    lines.append(f"`define WL_NUM_LAYERS {len(sizes)}")
    lines.append("`endif")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate weightless decoder Verilog from an exported model")
    parser.add_argument("model_json", type=pathlib.Path)
    parser.add_argument("-o", "--out-dir", type=pathlib.Path,
                        default=pathlib.Path(__file__).parent / "generated")
    args = parser.parse_args()

    with open(args.model_json) as f:
        model = json.load(f)
    meta, layers = model["meta"], model["layers"]
    name = args.model_json.name
    sizes = [len(l["mapping"]) for l in layers]
    assert sizes == meta["layer_sizes"], "layer sizes disagree with meta"

    args.out_dir.mkdir(parents=True, exist_ok=True)
    written = []

    in_bits = meta["input_size"]
    for i, layer in enumerate(layers, start=1):
        path = args.out_dir / f"dwn_layer{i}.sv"
        path.write_text(emit_layer(i, layer, in_bits, name))
        written.append(path)
        in_bits = len(layer["mapping"])

    for filename, text in (
        ("dwn_core.sv", emit_core(sizes, meta["input_size"], name)),
        ("dwn_params.svh", emit_params(meta, sizes, name)),
    ):
        path = args.out_dir / filename
        path.write_text(text)
        written.append(path)

    stale = [p for p in args.out_dir.glob("dwn_layer*.sv") if p not in written]
    for path in stale:
        path.unlink()

    print(f"{name}: n={meta['n']}, layers={sizes}, {sum(sizes)} lut nodes")
    for path in written:
        print(f"wrote {path}")
    for path in sorted(stale):
        print(f"removed stale {path}")


if __name__ == "__main__":
    main()
