// Generated by rtl/frontend/generate_rtl.py from circuit.stim; regenerate rather than edit.
`ifndef FRONTEND_PARAMS_SVH
`define FRONTEND_PARAMS_SVH

localparam int ANCILLAS = 8;
localparam int ROUNDS = 3;
localparam int DATA_QUBITS = 9;
localparam int DETECTORS = 24;
localparam int LAYER0_DETS = 4;
localparam int LAYER3_DETS = 4;
localparam int TAP_W = 3;

localparam logic [LAYER0_DETS*TAP_W-1:0] LAYER0_TAP = {3'd3, 3'd6, 3'd1, 3'd4};

localparam logic [LAYER3_DETS*TAP_W-1:0] LAYER3_TAP = {3'd3, 3'd6, 3'd1, 3'd4};
localparam logic [LAYER3_DETS*DATA_QUBITS-1:0] LAYER3_DATA = {9'h024, 9'h1b0, 9'h01b, 9'h048};

localparam logic [DATA_QUBITS-1:0] OBSERVABLE_DATA = 9'h007;

`endif
