"""Emits the detector-formation wiring for the syndrome frontend from the Stim circuit."""

import argparse
import pathlib

import stim

MEASURE = ("M", "MR", "MX", "MZ", "MRX", "MRZ", "MPP")


def measurement_blocks(circuit):
    blocks, count = [], 0
    for inst in circuit.flattened():
        if inst.name in MEASURE:
            width = len(inst.targets_copy())
            blocks.append((count, width))
            count += width
    return blocks


def detector_terms(circuit):
    dets, obs, count = [], None, 0
    for inst in circuit.flattened():
        if inst.name in MEASURE:
            count += len(inst.targets_copy())
        elif inst.name == "DETECTOR":
            dets.append(sorted(count + t.value for t in inst.targets_copy()))
        elif inst.name == "OBSERVABLE_INCLUDE":
            obs = sorted(count + t.value for t in inst.targets_copy())
    return dets, obs


def emit_params(name, ancillas, rounds, data_qubits, dets, l0, l3_tap, l3_data, obs):
    tap_w = max(1, (ancillas - 1).bit_length())

    def vector(decl, values, width):
        body = ", ".join(reversed(values))
        return f"{decl} {{{body}}};"

    taps = lambda v: [f"{tap_w}'d{a}" for a in v]
    masks = [f"{data_qubits}'h{m:0{(data_qubits + 3) // 4}x}" for m in l3_data]
    return "\n".join([
        f"// Generated by rtl/frontend/generate_rtl.py from {name}; regenerate rather than edit.",
        "`ifndef FRONTEND_PARAMS_SVH",
        "`define FRONTEND_PARAMS_SVH",
        "",
        f"localparam int ANCILLAS = {ancillas};",
        f"localparam int ROUNDS = {rounds};",
        f"localparam int DATA_QUBITS = {data_qubits};",
        f"localparam int DETECTORS = {dets};",
        f"localparam int LAYER0_DETS = {len(l0)};",
        f"localparam int LAYER3_DETS = {len(l3_tap)};",
        f"localparam int TAP_W = {tap_w};",
        "",
        vector("localparam logic [LAYER0_DETS*TAP_W-1:0] LAYER0_TAP =", taps(l0), tap_w),
        "",
        vector("localparam logic [LAYER3_DETS*TAP_W-1:0] LAYER3_TAP =", taps(l3_tap), tap_w),
        vector("localparam logic [LAYER3_DETS*DATA_QUBITS-1:0] LAYER3_DATA =", masks, data_qubits),
        "",
        f"localparam logic [DATA_QUBITS-1:0] OBSERVABLE_DATA = {data_qubits}'h{obs:0{(data_qubits + 3) // 4}x};",
        "",
        "`endif",
    ]) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate the syndrome frontend detector wiring")
    parser.add_argument("circuit", type=pathlib.Path)
    parser.add_argument("-o", "--out", type=pathlib.Path,
                        default=pathlib.Path(__file__).parent / "frontend_params.svh")
    args = parser.parse_args()

    circuit = stim.Circuit.from_file(args.circuit)
    blocks = measurement_blocks(circuit)
    rounds = len(blocks) - 1
    ancillas = blocks[0][1]
    data_base, data_qubits = blocks[-1]
    dets, obs = detector_terms(circuit)

    layer0 = [d[0] for d in dets if len(d) == 1]
    assert all(a < ancillas for a in layer0), "layer 0 taps outside the first round"

    middle = [d for d in dets if len(d) == 2]
    assert len(middle) == (rounds - 1) * ancillas, "middle layers are not one detector per ancilla"
    for i, (low, high) in enumerate(middle):
        assert high - low == ancillas and low == i, f"detector {i} is not the identity XOR"

    final = [d for d in dets if d[-1] >= data_base and len(d) > 1]
    layer3_tap, layer3_data = [], []
    for terms in final:
        ancilla = [t for t in terms if t < data_base]
        assert len(ancilla) == 1, "final detector does not reference exactly one ancilla"
        layer3_tap.append(ancilla[0] - (rounds - 1) * ancillas)
        mask = 0
        for t in terms:
            if t >= data_base:
                mask |= 1 << (t - data_base)
        layer3_data.append(mask)

    assert all(t >= data_base for t in obs), "observable references an ancilla measurement"
    obs_mask = 0
    for t in obs:
        obs_mask |= 1 << (t - data_base)

    args.out.write_text(emit_params(args.circuit.name, ancillas, rounds, data_qubits,
                                    len(dets), layer0, layer3_tap, layer3_data, obs_mask))

    print(f"{args.circuit.name}: {circuit.num_measurements} measurements -> {len(dets)} detectors")
    print(f"layers {len(layer0)} / {ancillas} / {ancillas} / {len(final)}, "
          f"{ancillas} ancillas x {rounds} rounds + {data_qubits} data")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
