"""Emits the frozen decoding-graph parameter file for the Union-Find decoder from a detector error model."""

import argparse
import pathlib
import sys

import stim

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "host" / "freeze"))
from unionfind_hw import UnionFindHW


def chunks(values, per):
    return [values[i:i + per] for i in range(0, len(values), per)]


def vector(decl, values, per):
    lines = [decl + " {"]
    groups = chunks(list(reversed(values)), per)
    for i, group in enumerate(groups):
        lines.append("    " + ", ".join(group) + ("," if i < len(groups) - 1 else ""))
    lines.append("};")
    return lines


def emit_params(hw, name):
    edges = len(hw.edge_ends)
    obs = 0
    for e, bit in enumerate(hw.edge_obs):
        obs |= int(bit) << e
    lines = [
        f"// Generated by rtl/union_find/generate_rtl.py from {name}; regenerate rather than edit.",
        "`ifndef UNION_FIND_PARAMS_SVH",
        "`define UNION_FIND_PARAMS_SVH",
        "",
        f"localparam int NODES = {hw.nodes};",
        f"localparam int EDGES = {edges};",
        f"localparam int NODE_W = {hw.node_bits};",
        f"localparam int EDGE_W = {hw.edge_bits};",
        f"localparam int BOUNDARY = {hw.boundary};",
        "",
    ]
    for field, end in (("EDGE_U", 0), ("EDGE_V", 1)):
        values = [f"{hw.node_bits}'d{int(e[end])}" for e in hw.edge_ends]
        lines += vector(f"localparam logic [EDGES*NODE_W-1:0] {field} =", values, 13) + [""]

    lines.append(f"localparam logic [EDGES-1:0] EDGE_OBS = {edges}'h{obs:0{(edges + 3) // 4}x};")
    lines.append("")

    masks = []
    for node in range(hw.nodes):
        mask = 0
        for edge in hw.incident[node]:
            mask |= 1 << int(edge)
        masks.append(f"{edges}'h{mask:0{(edges + 3) // 4}x}")
    lines += vector("localparam logic [NODES*EDGES-1:0] INC =", masks, 1) + [""]

    lines.append("`endif")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate the Union-Find decoding-graph parameters")
    parser.add_argument("model_dem", type=pathlib.Path)
    parser.add_argument("-o", "--out", type=pathlib.Path,
                        default=pathlib.Path(__file__).parent / "union_find_params.svh")
    args = parser.parse_args()

    hw = UnionFindHW(stim.DetectorErrorModel.from_file(args.model_dem))
    args.out.write_text(emit_params(hw, args.model_dem.name))

    print(f"{args.model_dem.name}: {hw.nodes} nodes, {len(hw.edge_ends)} edges, "
          f"{int(hw.edge_obs.sum())} carrying the observable")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
